### ISSUE TITLE
Unable to configure players with a space in their name

### ISSUE THREAD

**Issue by mariuszste** [FichteFoll/discordrp-mpris#33]
It seems to be impossible to configure players that have a space in their name since toml doesn't allow spaces in kay names. Or am I just missing something. If there is a way then documenting it would be a good idea

**Comment by FichteFoll** [comment]
TOML requires parts of sections to be quoted if they should contain spaces or dots, i.e.
```toml
[player."Spotify with Spaces"]
ignore = true
```

If you know of an existing player with spaces, I'll add it to the default config as an example, though commented.

**Comment by FichteFoll** [comment]
With dbeed4f6cc39ad5ad0d66469193c4103823e58b7, I have moved all currently known players that I have uploaded icons for into the default configuration, providing sufficient examples for how to configure players with spaces in their name. Due to an implementation detail, players with a `.` in their name are currently not supported, but I'm not aware of any at the moment.

**Comment by mariuszste** [comment]
Weird, I tried that. Well now it works, thanks
