### ISSUE TITLE
Firefox configuration title

### ISSUE THREAD

**Issue by BnDLett** [FichteFoll/discordrp-mpris#37]
Upon trying to add a configuration for Firefox, I either get an error or no results. This is what I've tried:
```
[player.Firefox]
[player.Mozilla Firefox] (this throws an error)
[player.MozillaFirefox]
[player.Mozilla-Firefox]
[player.Mozilla_Firefox]
```
It isn't an issue with my configuration file itself either, as I can add configurations for the global scope and the Strawberry media player.

**Comment by gaussandhisgun** [comment]
as mentioned in #33, you need to quote the player name if it has spaces

**Comment by BnDLett** [comment]
> as mentioned in #33, you need to quote the player name if it has spaces

Danke. I believe it would have been helpful if it was mentioned in the README.md file. Other than that, I believe my question is answered now, so I'll close this issue.

**Comment by FichteFoll** [comment]
Via dbeed4f6cc39ad5ad0d66469193c4103823e58b7 (also mentioned in #33), I have updated the example configuration but I haven't prepared a new release yet because I still want to do some changes before packing up a release and haven't yet found the time to do so, unfortunately.

Would having the default configuration with such an example have helped in your case or would you still say it should be mentioned in the README?

**Comment by BnDLett** [comment]
> Would having the default configuration with such an example have helped in your case or would you still say it should be mentioned in the README?

Having it in the example/default configuration would have helped my case, yes.
