### ISSUE TITLE
Cannot find config file on fedora

### ISSUE THREAD

**Issue by maybe-asdf** [FichteFoll/discordrp-mpris#38]
ive tried pip show -f discordrp-mpris
but that just returns a list of files i cannot find 
ive tried cd'ing into the directories but none contain the file... pls helpp
also the terminal says this on the title bar if that helps
![image](https://github.com/FichteFoll/discordrp-mpris/assets/161073330/ea2cb556-ab5c-4e58-a398-41d99862f341)

**Comment by BnDLett** [comment]
You're going to need to create the file yourself. From what I understand, the tool more than likely loads the default configuration first and then checks for an external configuration file. If that external configuration file exists, then it will load the configuration file and prioritize it's configuration over the default one. Running the following commands should work:
```
mkdir ~/.config/discordrp-mpris
nano ~/.config/discordrp-mpris/config.toml
```
The `mkdir` command will make a new directory and the `nano` command will open Fedora's terminal text editor. Although, if you prefer a different text editor, then you are welcome to use that instead. Just ensure that you go to the directory `~/.config/discordrp-mpris` and edit the file `config.toml`.

**Comment by FichteFoll** [comment]
Indeed, the default configuration is loaded first and then the user configuration is loaded from the [specified location](https://github.com/FichteFoll/discordrp-mpris#configuration) to override any values. The file needs to be created manually if it does not exist yet, since this is user-specific configuration and not something package managers deal with.
