### ISSUE TITLE
Problem when using mps-youtube and question about Spotify.

### ISSUE THREAD

**Issue by brunibunny** [FichteFoll/discordrp-mpris#4]
Hey man, great utility. But I'm afraid I'm having some issues with it.
When using [mps-youtube](https://github.com/mps-youtube/mps-youtube), which does support mpris2, discordrp-mpris exits with this error:

> [nipkow@nipkow-ln ~]$ discordrp-mpris 
INFO:discordrp_mpris.__main__:Connected to Discord client
WARNING:discord_rpc.async:closing connection
Traceback (most recent call last):
  File "/usr/bin/discordrp-mpris", line 11, in <module>
    load_entry_point('discordrp-mpris==0.1.1', 'console_scripts', 'discordrp-mpris')()
  File "/usr/lib/python3.6/site-packages/discordrp_mpris/__main__.py", line 236, in main
    loop.run_until_complete(wait_task)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/site-packages/discordrp_mpris/__main__.py", line 230, in main
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/discordrp_mpris/__main__.py", line 222, in main_async
    await instance.run()
  File "/usr/lib/python3.6/site-packages/discordrp_mpris/__main__.py", line 59, in run
    await self.tick()
  File "/usr/lib/python3.6/site-packages/discordrp_mpris/__main__.py", line 69, in tick
    player = await self.find_active_player()
  File "/usr/lib/python3.6/site-packages/discordrp_mpris/__main__.py", line 148, in find_active_player
    groups = await self.group_players(players)
  File "/usr/lib/python3.6/site-packages/discordrp_mpris/__main__.py", line 192, in group_players
    state = ampris2.PlaybackStatus(await p.player.PlaybackStatus)  # type: ignore
AttributeError: 'org.mpris.MediaPlayer2.Player' object has no attribute 'PlaybackStatus'

Not sure if there is anything wrong with mps-youtube's mpris implementation. It seems to work fine with other applications such as Cinnamon's "audio/sound" controller. 

Also, would it be possible to "disable" discordrp-mpris automatically when Spotify is running? It breaks Discord's integration with Spotify, preventing me from listening songs with friend and such.

**Comment by FichteFoll** [comment]
>Not sure if there is anything wrong with mps-youtube's mpris implementation.

From the traceback, it appears that mps-youtube doesn't fully implement the `org.mpris.MediaPlayer2.Player` interface. `PlaybackStatus` is [not an optional property](https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html). Looking at the [source code](https://github.com/mps-youtube/mps-youtube/blob/0100a38d3874c53e705d9acd7e30fbc6a3099da0/mps_youtube/mpris.py#L138), it doesn't actually seem to be implementing any properties at all and only has method definitions, but I'm not familiar with the `dbus` package. A quick check with QDBusViewer confirms this.

![2018-06-04_12-54-49](https://user-images.githubusercontent.com/931051/40913969-b6050f56-67f6-11e8-86d7-c9dd87241910.png)

Created https://github.com/mps-youtube/mps-youtube/issues/839 upstream.


>Also, would it be possible to "disable" discordrp-mpris automatically when Spotify is running?

Added a task to #2 for config to ignore certain players. Been thinking about that for a while, but time has been short which is why I didn't do any commits recently.
I didn't know Spotify had an mpris2 interface to begin with, though, so that's perfectly understandable.

**Comment by FichteFoll** [comment]
Actually, I believe I need to be more aggressive with Spotify running because it's a unique sitation. Will re-open for now.

**Comment by brunibunny** [comment]
Awesome, man. I will follow the upstream issue you created as well. Thank you so much for looking into this!

**Comment by brunibunny** [comment]
Everything is working smoothly now. No more crashes and Spotify is being ignored. Also, thank you for implementing the configuration options!
So, am I correct in assuming that mps-youtube and similarly weird players just are not compatible with discordrp-mpris? I'm not familiar with dbus, but from what I understood, hrnr said it's a dbus-python issue, right?
