### ISSUE TITLE
How to Change the Status Text

### ISSUE THREAD

**Issue by sirplatypos** [FichteFoll/discordrp-mpris#8]
I have been picking through the source code, and have located the definitions for everything but the status title itself ("Media (mpris2)").  I was wondering where/how to change this, specifically to say the player name instead.

**Comment by BobbyWibowo** [comment]
AFAIK you can't change that status message from Discord's RP SDK. It will always use the app name, which is set in your "application". In this case, since we're using Fichte's Client ID, the status name will be "Media (mpris2)", since that's the app name he defined. If you want to change that, the best option is to make your own "application" (https://discordapp.com/developers/applications/), then use its Client ID. However you will then have to re-upload all the assets (player and status icons).

**Comment by sirplatypos** [comment]
Thank you so much, I was going nuts trying to figure out where the pictures and such were. I may just make my own, since I only use cmus anyway.

**Comment by FichteFoll** [comment]
You can add multiple icons to an application. They are then selected with a string identifier.

See also #3.

**Comment by FichteFoll** [comment]
FWIW, I intend to make the client ID a configuration option and have player-specific overrides for #3, so you will be able to change the app more easily. 

Closing as a duplicate.
